Add diagnostic logs
wso2-extensions/identity-local-auth-magiclink pull request #36
Opened 2023-07-31 12:18 UTC by sahandilshan

## Purpose
* $subject

### Approach

![image](https://github.com/wso2-enterprise/asgardeo-product/assets/32576163/ceea5959-581e-47aa-b7b2-6962861a2b2d)

Diagnostic logs will be covered the green-colored actions/validations of the authentication process. 
1. Authentication Request Validation
Within each authenticator, the `initiateAuthenticationRequest` method houses the logic for this step. This triggers two diagnostic logs. The first log indicates when authentication validation starts, and the second log shows the result of the validation – whether it's a Success or marked Invalid.

2. Validate Authentication Response
The `processAuthenticationResponse` method handles authentication response validation. Once users are sent to the authentication page and complete the process, the authenticator receives an authentication response, which this method manages. Just like the request validation, this step also generates two diagnostic logs. The first one marks the beginning of response validation, while the second one is only created if the authentication is successful. We've chosen not to include logs for authentication response failures for a couple of reasons:
- Numerous potential failure scenarios across authenticators make adding logs for each too complicated and code-heavy.
- With https://github.com/wso2/carbon-identity-framework/pull/4809, there's a common log in place that covers and reports authentication response failures caused by authenticators.

Additionally, there will be another diagnostic log that will get published from the canHandle() method of each authenticator. The `canHandle` method gets executed each time before the `initiateAuthenticationRequest` and `processAuthenticationResponse` get executed. This log is published as an internal log for our internal developers. The purpose of this log is to verify whether the auth request/response was passed into the authenticator to handle it.

2023-07-31 13:09 UTC, Yoshani requested changes

2023-07-31 14:34 UTC, ThaminduR commented on components/org.wso2.carbon.identity.application.authenticator.magiclink/src/main/java/org/wso2/carbon/identity/application/authenticator/magiclink/MagicLinkAuthenticator.java
> +        // the flow
End comments with `.` Check other places as well

2023-07-31 14:42 UTC, ThaminduR commented on components/org.wso2.carbon.identity.application.authenticator.magiclink/src/main/java/org/wso2/carbon/identity/application/authenticator/magiclink/MagicLinkAuthenticator.java
> +     */
add return type desc.

2023-07-31 15:03 UTC, sahandilshan commented on components/org.wso2.carbon.identity.application.authenticator.magiclink/src/main/java/org/wso2/carbon/identity/application/authenticator/magiclink/MagicLinkAuthenticator.java
> +            boolean canHandle = StringUtils.isNotEmpty(userName) || StringUtils.isNotEmpty(restart);
In the two occasions canHandle method has two different flows. So we cannot take it to a common place.

2023-07-31 15:04 UTC, sahandilshan commented on components/org.wso2.carbon.identity.application.authenticator.magiclink/src/main/java/org/wso2/carbon/identity/application/authenticator/magiclink/MagicLinkAuthenticator.java
> +     */
Fixed with ff2e61c44911bda5bed47d34cdf60e8826f797e0

2023-07-31 15:04 UTC, sahandilshan commented on components/org.wso2.carbon.identity.application.authenticator.magiclink/src/main/java/org/wso2/carbon/identity/application/authenticator/magiclink/MagicLinkAuthenticator.java
> +import static org.wso2.carbon.identity.application.authenticator.magiclink.MagicLinkAuthenticatorConstants.*;
Fixed with ff2e61c44911bda5bed47d34cdf60e8826f797e0

2023-07-31 15:04 UTC, sahandilshan commented on components/org.wso2.carbon.identity.application.authenticator.magiclink/src/main/java/org/wso2/carbon/identity/application/authenticator/magiclink/MagicLinkAuthenticator.java
> +        // the flow
Fixed with ff2e61c44911bda5bed47d34cdf60e8826f797e0

2023-08-10 10:52 UTC, chamathns commented on components/org.wso2.carbon.identity.application.authenticator.magiclink/src/main/java/org/wso2/carbon/identity/application/authenticator/magiclink/MagicLinkAuthenticator.java
> +        DiagnosticLog.DiagnosticLogBuilder finalDiagnosticLogBuilder = null;
shall we go with something like `baseLogBuilder`? The idea, is we have the basic builder elements which we are going to publish in all of the diagnostic logs in the class. Hence it is acting as a base

2023-08-10 11:00 UTC, chamathns commented on components/org.wso2.carbon.identity.application.authenticator.magiclink/src/main/java/org/wso2/carbon/identity/application/authenticator/magiclink/MagicLinkAuthenticator.java
> +            return Optional.empty();
```suggestion
        return Optional.ofNullable(context.getSubject())
                   .map(subject -> {
                       try {
                           return subject.getUserId();
                       } catch (UserIdNotFoundException e) {
                           logIfDebugEnabled("Error while getting the user id from the subject.", e);
                           return null;
                       }
                   });
```

2023-08-10 11:17 UTC, chamathns approved these changes

2023-08-10 11:32 UTC, sahandilshan commented on components/org.wso2.carbon.identity.application.authenticator.magiclink/src/main/java/org/wso2/carbon/identity/application/authenticator/magiclink/MagicLinkAuthenticator.java
> +            return Optional.empty();
Fixed with 30d1ff29823952511ec77d53b2c776c283577eb2

2023-08-10 11:42 UTC, chamathns approved these changes

2023-08-11 03:50 UTC, merged